[project]
name = "inspect-proxmox-sandbox"
version = "0.2.0"
description = ""
readme = "README.md"
authors = [
    {name = "UK AI Safety Institute"}
]
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.3",
    "tenacity>=9.0.0",
    "httpx>=0.28.1",
    "pydantic>=2.10.6",
    "pycdlib>=1.14.0",
    "pydantic-extra-types>=2.10.2",
    "pycurl>=7.45.0",
]

[project.entry-points."inspect_ai"]
"proxmox-sandbox" = "proxmoxsandbox.inspect.proxmox_sandbox_environment"

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = ["tests"]
testpaths = ["tests/**/*.py"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/proxmoxsandbox"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.ruff]
target-version = "py310"

[tool.mypy]
python_version = "3.10"
plugins = "pydantic.mypy"
packages = ["proxmoxsandbox", "tests.proxmoxsandboxtest"]

[dependency-groups]
dev = [
    "aisitools @ git+ssh://git@github.com/AI-Safety-Institute/aisi-inspect-tools",
    "inspect-ai @ git+ssh://git@github.com/UKGovernmentBEIS/inspect_ai@main",
    "mypy>=1.14.1",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.3",
    "ruff>=0.9.3",
]
